name: terraform_destroy
label: Destroy Topology
description: Destroys this topology
type: docker
labels:
    collection: Example Skillets
variables: []
snippets:
-   name: terraform_destroy
    image: registry.gitlab.com/panw-gse/as/terraform_tools:0.14
    tag: '0.14'
    cmd: destroy --auto-approve -no-color
