variable "Azure_Region" {}
variable "Admin_Username" {}
variable "Admin_Password" {}
variable "resource_group_name" {}
variable "Bootstrap_Storage_Account" {}
variable "Storage_Account_Access_Key" {}
variable "Storage_Account_Fileshare" {}
variable "Storage_Account_Fileshare_Directory" {}
variable "Web_Initscript_Path" {}
variable "Attack_Initscript_Path" {}
variable "Victim_CIDR" {}
variable "Attack_CIDR" {}
variable "Mgmt_Subnet_CIDR" {}
variable "Untrust_Subnet_CIDR" {}
variable "Trust_Subnet_CIDR" {}
variable "AppGW_Subnet_CIDR" {}
variable "Web_Subnet_CIDR" {}
variable "Attack_Subnet_CIDR" {}
variable "FW_Mgmt_IP" {}
variable "FW_Untrust_IP" {}
variable "FW_Trust_IP" {}
variable "WebLB_IP" {}
variable "client_01_mgmt_ip" {}
variable "client_01_trust_ip" {}
variable "client_02_mgmt_ip" {}
variable "client_02_trust_ip" {}